---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-repo
spec:
  type: git
  params:
  - name: url
    value: http://github.com/meidlinger/sdgdemoboot.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/employee/springboot-demo:latest
