apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: springboot-demo
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: springboot-demo
    template:
      name: springboot-demo
