apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: employee-app
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: employee-app
    template:
      name: employee-app
